"use client";
import { mockBlogContent } from "@/lib/mockData";

export default function ContentEditor() {
  return (
    <div className="flex-1 overflow-y-auto" style={{ background: "var(--bg)" }}>
      <div className="max-w-3xl mx-auto px-12 py-16">
        
        {/* Status Badge */}
        <div className="flex items-center gap-2 mb-12">
          <div className="w-1.5 h-1.5 rounded-full" style={{ background: "var(--accent-success)" }} />
          <span className="text-xs font-semibold" style={{ color: "var(--muted)" }}>
            AI-GENERATED DRAFT
          </span>
        </div>

        {/* Title - MOST PROMINENT */}
        <h1 className="text-5xl font-bold leading-tight mb-8" style={{ color: "var(--text)" }}>
          {mockBlogContent.title}
        </h1>

        {/* Subtitle */}
        <p className="text-lg leading-relaxed mb-12" style={{ color: "var(--text-secondary)" }}>
          {mockBlogContent.metaDescription}
        </p>

        {/* Meta Tags - Subtle */}
        <div className="flex gap-2 mb-16 pb-12 border-b" style={{ borderColor: "var(--border)" }}>
          <span className="text-xs px-2.5 py-1 rounded" style={{ background: "var(--elevated)", color: "var(--muted)" }}>
            2,140 words
          </span>
          <span className="text-xs px-2.5 py-1 rounded" style={{ background: "var(--elevated)", color: "var(--muted)" }}>
            9 min read
          </span>
          <span className="text-xs px-2.5 py-1 rounded" style={{ background: "var(--elevated)", color: "var(--muted)" }}>
            SEO Score: 87
          </span>
        </div>

        {/* Content */}
        <div className="space-y-12">
          {mockBlogContent.sections.map((section, i) => (
            <div key={i}>
              <h2 className="text-2xl font-bold mb-6" style={{ color: "var(--text)" }}>
                {section.heading}
              </h2>
              <div className="space-y-4 leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                {section.content.split("\n\n").map((para, j) => (
                  <p key={j} className="text-base">{para}</p>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Featured Image */}
        <div className="mt-16 rounded-lg overflow-hidden border" style={{ borderColor: "var(--border)" }}>
          <div className="w-full h-64 bg-gradient-to-br from-slate-700 to-slate-900" />
        </div>

        {/* FAQ Section */}
        <div className="mt-16 pt-12 border-t" style={{ borderColor: "var(--border)" }}>
          <h2 className="text-2xl font-bold mb-8" style={{ color: "var(--text)" }}>
            Frequently Asked Questions
          </h2>
          <div className="space-y-3">
            {mockBlogContent.faqs.map((faq, i) => (
              <details key={i} className="card p-5 cursor-pointer group"
                style={{ background: "var(--surface)" }}>
                <summary className="font-semibold flex items-center justify-between" style={{ color: "var(--text)" }}>
                  {faq.q}
                  <span className="text-lg group-open:rotate-180 transition-transform" style={{ color: "var(--accent)" }}>›</span>
                </summary>
                <p className="mt-4 text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
                  {faq.a}
                </p>
              </details>
            ))}
          </div>
        </div>

        {/* CTA Block */}
        <div className="mt-16 p-8 rounded-lg border" style={{ background: "var(--elevated)", borderColor: "var(--border)" }}>
          <h3 className="text-lg font-bold mb-3" style={{ color: "var(--text)" }}>
            Ready to generate more?
          </h3>
          <p className="text-sm mb-6" style={{ color: "var(--text-secondary)" }}>
            Create another SEO-optimized blog post in minutes.
          </p>
          <button className="btn-primary">
            Generate New Blog →
          </button>
        </div>

        {/* Footer */}
        <div className="text-center py-12 mt-16 border-t" style={{ borderColor: "var(--border)", color: "var(--muted)" }}>
          <p className="text-xs">
            Generated by Blogy AI • {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
}
